services:
    app.tweet.manager:
        class: AppBundle\Manager\TweetManager
        arguments:
               - "@=service('doctrine').getManager()"
               - "%app.tweet.nb_last%"

    app.tweet.messenger:
        class: AppBundle\Messenger\EmailMessenger
        arguments:
             - "@mailer"